/*
===============================================================================
Stored Procedure: Load Silver Layer (Bronze -> Silver)
===============================================================================
Script Purpose:
    This stored procedure performs the ETL (Extract, Transform, Load) process to 
    populate the 'silver' schema tables from the 'bronze' schema.
	Actions Performed:
		- Truncates Silver tables.
		- Inserts transformed and cleansed data from Bronze into Silver tables.
		
Parameters:
    None. 
	  This stored procedure does not accept any parameters or return any values.

Usage Example:
    CALL Silver.load_silver();
===============================================================================
*/



DROP PROCEDURE IF EXISTS silver.load_silver();

CREATE PROCEDURE silver.load_silver()
LANGUAGE plpgsql
AS $$
BEGIN

	--LOADING SILVER.CRM_CUST_INFO
	TRUNCATE TABLE SILVER.CRM_CUST_INFO;
	INSERT INTO SILVER.CRM_CUST_INFO (
		CST_ID,
		CST_KEY,
		CST_FIRSTNAME,
		CST_LASTNAME,
		CST_MARITAL_STATUS,
		CST_GNDR,
		CST_CREATE_DATE
	)
	SELECT
		CST_ID,
		CST_KEY,
		TRIM(CST_FIRSTNAME) AS CST_FIRSTNAME,
		TRIM(CST_LASTNAME) AS CST_LASTNAME,
		CASE
			WHEN TRIM(CST_MARITAL_STATUS) = 'M' THEN 'MARRIED'
			WHEN TRIM(CST_MARITAL_STATUS) = 'S' THEN 'SINGLE'
			ELSE 'UNKNOWN'
		END CST_MARITAL_STATUS, --NORMALIZE MARITAL STATUS IN READABLE MODE
		CASE
			WHEN TRIM(CST_GNDR) = 'F' THEN 'FEMALE'
			WHEN TRIM(CST_GNDR) = 'M' THEN 'MALE'
			ELSE 'UNKNOWN'
		END CST_GNDR, --NORMALIZE GENDER IN READABLE MODE
		CST_CREATE_DATE
	FROM
		(
			SELECT
				*,
				ROW_NUMBER() OVER (
					PARTITION BY
						CST_ID
					ORDER BY
						CST_CREATE_DATE DESC
				) AS FLAG_LAST
			FROM
				BRONZE.CRM_CUST_INFO
			WHERE
				CST_ID IS NOT NULL
		) --MAKING CST_ID AS THE PRIMARY KEY BY REMOVING NULL AND DUPLICATE VALUES
	WHERE
		FLAG_LAST = 1;

	--LOADING SILVER.CRM_PRD_INFO
	
	TRUNCATE TABLE SILVER.CRM_PRD_INFO ;
	INSERT INTO 
	SILVER.CRM_PRD_INFO (
		PRD_ID ,
		CAT_ID,
		PRD_KEY ,
		PRD_NM ,
		PRD_COST ,
		PRD_LINE ,
		PRD_START_DT ,
		PRD_END_DT
	)
	SELECT 
		PRD_ID ,
		REPLACE(SUBSTRING(PRD_KEY,1,5),'-','_') AS CAT_ID,
		SUBSTRING(PRD_KEY,7)AS PRD_KEY,
		PRD_NM ,
		COALESCE(PRD_COST,0) AS PRD_COST,
		CASE TRIM(PRD_LINE)
				WHEN 'M' THEN 'MOUNTAIN'
				WHEN 'R' THEN 'ROAD'
				WHEN 'S' THEN 'OTHER SALES'
				WHEN 'T' THEN 'TOURING'
				ELSE 'UNKNOWN'
		END AS PRD_LINE,
		PRD_START_DT,
		(lead(prd_start_dt)
		over(partition by PRD_KEY ORDER BY PRD_START_DT) -1) as 
		PRD_END_DT
	FROM BRONZE.CRM_PRD_INFO ;

	--LOADING SILVER.CRM_SALES_DETAILS

	TRUNCATE TABLE SILVER.CRM_SALES_DETAILS;
	INSERT INTO SILVER.CRM_SALES_DETAILS(
		SLS_ORD_NUM,
		SLS_PRD_KEY,
		SLS_CUST_ID,
		SLS_ORDER_DT,
		SLS_SHIP_DT,
		SLS_DUE_DT,
		SLS_SALES,
		SLS_QUANTITY,
		SLS_PRICE
	)
	
	SELECT
		SLS_ORD_NUM,
		SLS_PRD_KEY,
		SLS_CUST_ID,
		CASE
			WHEN SLS_ORDER_DT = 0
			OR LENGTH(CAST((SLS_ORDER_DT) AS TEXT)) != 8 THEN NULL
			ELSE CAST(CAST(SLS_ORDER_DT AS TEXT) AS DATE)
		END AS SLS_ORDER_DT, --CHECKING THE NULL AND ZERO VALUES AND CONVERTING THE
		CAST(CAST(SLS_SHIP_DT AS TEXT) AS DATE), --CAST THE INT TO TEXT THEN DATE
		CAST(CAST(SLS_DUE_DT AS TEXT) AS DATE), --CAST THE INT TO TEXT THEN DATE
		CASE
			WHEN SLS_SALES IS NULL
			OR SLS_SALES <= 0
			OR SLS_SALES != (SLS_QUANTITY * ABS(SLS_PRICE)) THEN SLS_QUANTITY * ABS(SLS_PRICE)
			ELSE SLS_SALES
		END AS SLS_SALES,
		SLS_QUANTITY,
		CASE
			WHEN SLS_PRICE IS NULL THEN (SLS_SALES / SLS_QUANTITY)
			ELSE ABS(SLS_PRICE)
		END SLS_PRICE
	FROM
		BRONZE.CRM_SALES_DETAILS;

	--LOADING SILVER.ERP_CUST_AZ12

	TRUNCATE TABLE SILVER.ERP_CUST_AZ12;
	INSERT INTO SILVER.ERP_CUST_AZ12(
		CID,
		BDATE,
		GEN
	)
	SELECT 
		CASE 
			WHEN CID LIKE 'NAS%' 
			THEN SUBSTRING(CID,4,LENGTH(CID))
			ELSE CID
		END CID, --DATA STANDERLIZATION
		case 
			when BDATE > current_date then null
			else BDATE
		END BDATE,
		CASE 
			WHEN TRIM(GEN) IN ('M','Male') THEN 'MALE'
			WHEN TRIM(GEN) IN ('F','Female') THEN 'FEMALE'
			ELSE 'UNKNOWN'
		END GEN
	FROM BRONZE.ERP_CUST_AZ12 ;

	--LOADING SILVER.ERP_LOC_A101
	
	TRUNCATE TABLE SILVER.ERP_LOC_A101;
	INSERT INTO SILVER.ERP_LOC_A101(
		CID,
		CNTRY
	)
	
	SELECT DISTINCT
	REPLACE(CID,'-','') AS CID,
	CASE 
		WHEN TRIM(CNTRY) = ('DE') 
		THEN 'Germany'
		WHEN TRIM(CNTRY) IN ('US', 'USA')
		THEN 'United States'
		WHEN TRIM(CNTRY) IS NULL OR TRIM(CNTRY)='' THEN 'Unknown'
		ELSE CNTRY
	END CNTRY
	FROM BRONZE.ERP_LOC_A101 ;

	--LOADING SILVER.ERP_PX_CAT_G1V2

	TRUNCATE TABLE SILVER.ERP_PX_CAT_G1V2;
	INSERT INTO SILVER.ERP_PX_CAT_G1V2(
		ID,
		CAT,
		SUBCAT,
		MAINTANCE
	)
	
	SELECT
		ID,
		CAT,
		SUBCAT,
		MAINTANCE
	FROM BRONZE.ERP_PX_CAT_G1V2;

	
END;
$$;
